#!/usr/bin/env bash
# Reads /etc/passwd and displays username, user id, and home directory
while IFS=: read -r username _ uid _ _ homedir _; do
    echo "${username}:${uid}:${homedir}"
done < /etc/passwd
