#!/usr/bin/env bash
#script that displays The content of the current directory in a list format where only the part of the name after the first dash is displayed

for file in *; do
    
    [ -e "$file" ] || continue

    after_dash="${file#*-}"

    echo "$after_dash"
done
