#!/usr/bin/env bash
# Creates a PID file, displays messages, and handles signals

# Create PID file
echo $$ > /var/run/myscript.pid

# Trap signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
